name: OpenGe CI
on: [push]
jobs:
  Deploy:
    runs-on: node:alpine
    steps:
      - run: yarn && yarn build
      - name: Deploy with FTP
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.ftp_host }}
          username: ${{ secrets.ftp_username }}
          password: ${{ secrets.ftp_password }}
          local-dir: ./out/
